# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Data wRangling for Ecologists
description:      'Using data science tools for exploration, analysis, and research'
url:              http://gge-ucd.github.io/wRangling-Ecology
baseurl:          /wRangling-Ecology
email:            rapeek@ucdavis.edu
feedbackurl:      https://docs.google.com/forms/d/e/1FAIpQLSeVawmCytz3b03YSIGRBwJMl463SkLFHDQUO0e0GQ3xIsKRTw/viewform
author:
  name:           'Ryan Peek'
  url:            https://ryanpeek.github.io

github:
  repo:           https://github.com/gge-ucd/wRangling-Ecology
  #               Be sure the 'Issues' feature is activated in 'Settings'
